### ISSUE TITLE
EarTrumpet holds some programs in use (Twitch, Spotify, Telegram, etc.)

### ISSUE THREAD

**Issue by shinji257** [File-New-Project/EarTrumpet#273]
I actually don't know what is happening here but when Twitch goes to update it throws a sharing violation in its logs on Twitch.exe even though the app isn't running at all.  I thought it was due to a bugged self-updater but I tried running the actual updater directly and it still halted.  At that point prior diagnosis (Using Process Explorer) showed that EarTrumpet did hold a handle on Twitch.exe even when the program was closed so I closed EarTrumpet this time (after the manual update attempt) and it went straight through.

There are a few possible scenarios here and I'm not sure how easy it is to test.  Note that this has literally only happened with Twitch so if there is anything you want me to do then please ask.

1) A handle is grabbed when the app starts playing audio (aka stream) and is failing to release the handle for some reason when the app is killed by the updater.
2) A handle is grabbed when EarTrumpet redirects the audio for the app.

Most likely the next opportunity to debug will be when it needs to update but in the meantime I'll try to see if I can get the issue to trigger.  If memory serves I think I had trouble deleting the file even via Windows Explorer so...

**Comment by shinji257** [comment]
Already got a reproduction but my original diagnosis may have been wrong.  It does seem to release the handle eventually but while it is holding it is blocking file interactions.

Anyways to make it not blocking?  I will have to wait for the next update to see if the message does clear eventually or if I was just impatient.

**Comment by riverar** [comment]
Related #257 

Fixed this in ba9b3d17cbaad8a4146a8790f4a6b97038304fb6; we'll get this uploaded to the Store so it can go out in the next few days. Thanks for your patience!

**Comment by shinji257** [comment]
Ahh ok.  That makes sense.  I did mention earlier I saw the open handle after the executable closed so now that explains why.  Thanks for the update. 👍

**Comment by gate1975mlm** [comment]
I have a simular issue when trying to update Spotify too. 

When I try and update Spotify it keeps giving me some kind of error and says Spotify is in use and I should close it even though it already is closed and not running. Now that I think about it I think this issue started around the time I first started using EarTrumpet.

Hopefully the new EarTrumpet update fixes this issue with updating Spotify too.

**Comment by whoiskevinrich** [comment]
Any update on this? I'm still having the issue. From [this reddit thread](https://www.reddit.com/r/Twitch/comments/8s8jft/twitch_desktop_app_stuck_updating/) it seems like it's fairly common. 

I installed the windows app, but haven't seen an update that resolves the issue yet.

**Comment by riverar** [comment]
Hey all! This got fixed in EarTrumpet 2.0.5.0, went out August 1. Are you still seeing this issue in that version?

**Comment by gate1975mlm** [comment]
Not fixed for me with EarTrumpet 2.0.5.0 and latest update from Spotify!

I am using EarTrumpet 2.0.5.0 and I just tried updating desktop version of Spotify and it gave men an error and just hanged. As soon as I exited EarTrumpet and restarted Spotify the update installed.

riverar can you please install desktop version of Spotify and then try updating it with EarTrumpet 2.0.5.0 running and you should see the same issue as I am seeing. There was a new Spotify update just released to get it click the 3 whote dots in the upper left corner and then highlight Help and then about Spotify and it will say "update available" or something like that I think.

**Comment by gate1975mlm** [comment]
Actually now that I think about it my issue with Spotify not updating may be be a completely different issue then shinji257 with his Twitch issue?

Even if I am not playing any music but still have Spotify open it is showing in EarTrumpet. So I guess that is why Spotify will not update. Can this be fixed are will I always need to make sure EarTrumpet is not running before attempting to update Spotify?

**Comment by stevehoek** [comment]
Still an issue for me as well in 2.0.5 when trying to update Spotify

**Comment by shinji257** [comment]
Sorry for the late response but I forced an update on Twitch finally and it is still present on 2.0.5.0 here as well.

**Comment by rebel2k** [comment]
I second that, it's still present for me too, at least for Spotify (I didn't have problem updating the Twitch app recently).

**Comment by riverar** [comment]
I've seen many instances where Spotify is locked by the Windows kernel, probably a result of some driver or anti-virus. So we'll need to verify EarTrumpet is the culprit here.

Whenever this locking occurs, please do the following:
1. Download/run https://live.sysinternals.com/procexp.exe as Administrator
2. Find EarTrumpet.exe and click it
3. Ensure the bottom pane is showing open handles (View > Lower Pane View > Handles)
4. File > Save As > EarTrumpet.txt (or anything)
5. Drag/drop that file into this GitHub issue.

Thanks!

**Comment by shinji257** [comment]
Ok.  So I went and did this for Twitch and I can confirm that EarTrumpet.exe does not hold the handle when the program exits.  However the handle remains on PID 4.  However as soon as I close EarTrumpet I see that handle disappear from that PID even though it isn't on EarTrumpet itself.

**Comment by riverar** [comment]
@shinji257 Interesting. Can I reproduce your steps here? Do I just need to launch EarTrumpet, then Twitch?

**Comment by riverar** [comment]
I can reproduce this, thank you. How strange. Investigating further.

Repro steps:
1. Start Twitch
2. Start EarTrumpet
3. Exit Twitch
4. Note System has open handle to Twitch.exe
5. Exit EarTrumpet, note handle is closed

**Comment by rebel2k** [comment]
Yep, for the record, I also did the following test:
1. Start Spotify, update available.
2. Click on download update and restart.
3. Install never ends.
4. Kill it, restart Spotify. Install doesn't go further.
5. Close EarTrumpet.
6. Restart Spotify ==> Install works.

Hope you'll be able to find what's wrong! :)

**Comment by xintron** [comment]
Also having these issues with some applications like Spotify and Telegram (after media playback has been used). Closing EarTrumpet allows both Spotify and Telegram to successfully upgrade.

**Comment by riverar** [comment]
We've identified the problem and contacted Microsoft. Will provide more info as we receive it. (It's a holiday weekend for us, so likely won't hear anything until Tuesday sadly.)

**Comment by gate1975mlm** [comment]
Is this fixed yet?

Thanks

**Comment by riverar** [comment]
Not yet, still working with Microsoft on this.

**Comment by stevek123** [comment]
@riverar Do you know anything about the status of the fix?

**Comment by riverar** [comment]
Microsoft is aware of the issue but only have a fix for the next release of Windows 10 (19H1). I'm still pushing them to get a patch for us on Windows 10 October Update (1809).

**Comment by riverar** [comment]
Microsoft has confirmed a fix cannot be made for Windows 10 October Update (1809). We're researching potential workarounds. 😓

**Comment by WhAtEvErYoUmEaN** [comment]
@riverar You could try `(Icon)Icon.FromHandle(iconHandle).Clone()` which immediately releases the handle at the expense of storing an icon copy in your own memory space.

I haven't tried it with EarTrumpet yet but had a similiar problem with a viewer i wrote to get icons out various windows DLLs.

**Comment by shinji257** [comment]
I'm going to add that Twitch seems to have resolved it on their end.  I got an update just recently to their launcher and it went through without closing EarTrumpet first or throwing an error.  I don't believe it could have been anything else yet given the information in this thread.

**Comment by riverar** [comment]
@WhAtEvErYoUmEaN Appreciate you looking into it, however Microsoft has confirmed this is a fundamental issue with Desktop Bridge and the way they shim file system access. We are, however, considering a workaround that involves running our icon logic through an external broker. Just waiting for Microsoft to get back to us.

**Comment by stevek123** [comment]
@riverar Is there any hope that a fix will be included in 19H1?

**Comment by DeVaulted** [comment]
Any news for this bug? Otherwise it might be nice for a little pop-up or similar to be triggered the first time you start Spotify/any affected app with EarTrumpet running, it took me ages to figure out why Spotify wasn't updating properly.

**Comment by stevehoek** [comment]
I don't experience this problem anymore on Windows 10 1903 and latest version of EarTrumpet.
Amazon Music and Spotify both update correctly while EarTrumpet is running.

**Comment by DeVaulted** [comment]
@stevehoek Interesting, for some reason my Windows hadn't automatically updated to 1903. Doing that right now, will report again in case the issue still happens. Until then, ignore everything I said 😬

**Comment by riverar** [comment]
Yep, upgrading to 1903 will resolve this for you. Going to close this as 1903 is available for download.
